#include "app/GameBuilder.hpp"
#include "core/Scene.hpp"
#include "app/EmbeddedTemplate.hpp"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

#include <nlohmann/json.hpp>

#if defined(__EMSCRIPTEN__)
#include <emscripten.h>
#endif

#if defined(_WIN32) && !defined(__EMSCRIPTEN__)
#include <windows.h>
#include <shlobj.h>
#endif

// Game HTML shell generated by GameBuilder for every web export.
// Kept here so it's always fresh — the pre-built HTML in the game template bundle
// is old and does not carry the scene-injection hook.
// The sentinel "var __COWENGINE_SCENE__ = null;" is replaced at export time with
// "var __COWENGINE_SCENE__ = atob('BASE64SCENE');" so the correct scene loads.
static const char kGameHtmlTemplate[] =
R"html(<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover">
    <title>CowEngine Game</title>
    <style>
        html,body{height:100%;margin:0;background:#000;color:#eee;font-family:Arial,sans-serif;overflow:hidden;overscroll-behavior:none;}
        body{display:flex;flex-direction:column;}
        #main{position:relative;flex:1 1 auto;display:flex;}
        #canvas{display:block;width:100%;height:100%;background:#000;outline:none;touch-action:none;}
        .overlay{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;text-align:center;}
        #loadingOverlay{background:#000;z-index:40;flex-direction:column;}
        #startOverlay{background:rgba(0,0,0,0.6);z-index:30;cursor:pointer;font-size:22px;color:#fff;}
        #startOverlay .hint{font-size:14px;color:#bbb;margin-top:12px;}
        /* On-screen touch controls: above the canvas, below the start overlay. */
        #touchControls{position:absolute;inset:0;z-index:20;display:none;touch-action:none;-webkit-user-select:none;user-select:none;-webkit-tap-highlight-color:transparent;}
        #touchControls.on{display:block;}
        #stick{position:absolute;width:124px;height:124px;margin:-62px 0 0 -62px;border-radius:50%;border:2px solid rgba(255,255,255,0.25);background:rgba(255,255,255,0.07);opacity:0.4;transition:opacity .15s ease;}
        #stick.active{opacity:1;}
        #stickKnob{position:absolute;left:50%;top:50%;width:56px;height:56px;margin:-28px 0 0 -28px;border-radius:50%;background:rgba(255,255,255,0.45);border:1px solid rgba(255,255,255,0.5);}
        .touch-btn{position:absolute;width:78px;height:78px;border-radius:50%;border:2px solid rgba(255,255,255,0.3);background:rgba(255,255,255,0.1);color:#fff;font:600 13px/1 Arial,sans-serif;letter-spacing:.06em;opacity:0.75;}
        .touch-btn.held{background:rgba(255,255,255,0.3);opacity:1;}
        #jumpBtn{right:26px;bottom:calc(34px + env(safe-area-inset-bottom,0px));}
        #shootBtn{right:116px;bottom:calc(92px + env(safe-area-inset-bottom,0px));}
        /* Settings gear. Small and out of the way at the top — it opens a modal
           menu, so unlike the action buttons it is never pressed in a hurry. */
        #menuBtn{width:46px;height:46px;right:20px;top:calc(20px + env(safe-area-inset-top,0px));font-size:20px;}
    </style>
</head>
<body>
    <div id="main">
        <canvas id="canvas" tabindex="0"></canvas>
        <div id="loadingOverlay" class="overlay">
            <div>
                <div style="font-size:24px;margin-bottom:12px;">Loading...</div>
                <div style="font-size:13px;color:#888;">Decompressing assets</div>
            </div>
        </div>
        <div id="startOverlay" class="overlay" style="display:none;">
            <div>
                <div>Click to play</div>
                <div class="hint">WASD to move, mouse to look, Space to jump, Esc for settings, Tab to release cursor</div>
            </div>
        </div>
        <div id="touchControls">
            <div id="stick"><div id="stickKnob"></div></div>
            <button id="jumpBtn" class="touch-btn" type="button">JUMP</button>
            <button id="shootBtn" class="touch-btn" type="button">SHOOT</button>
            <button id="menuBtn" class="touch-btn" type="button">&#9881;</button>
        </div>
    </div>
    <script>
        var __COWENGINE_SCENE__ = null;
        var __COWENGINE_SCRIPTS__ = null;
        var __COWENGINE_MODELS__ = null;
        // Write the exported assets to localStorage before CowEngine.js loads so
        // the C++ localStorage mechanism picks them up without any EM_ASM global
        // reads. Scripts and models are seeded the same way as the scene so the
        // exported game's restoreAssetsFromLocalStorage() finds the latest edits.
        // Unprefixed keys on purpose: this shell carries no CowNet shim, so every
        // export from here is single-player and Scene::storageKey() resolves to
        // exactly these names. Adding multiplayer to this template means seeding
        // the 'cowengine_mp_' keys instead.
        if (typeof __COWENGINE_SCENE__ === 'string' && __COWENGINE_SCENE__) {
            try { localStorage.setItem('cowengine_save', __COWENGINE_SCENE__); } catch(e) {}
        }
        if (typeof __COWENGINE_SCRIPTS__ === 'string' && __COWENGINE_SCRIPTS__) {
            try { localStorage.setItem('cowengine_scripts', __COWENGINE_SCRIPTS__); } catch(e) {}
        }
        if (typeof __COWENGINE_MODELS__ === 'string' && __COWENGINE_MODELS__) {
            try { localStorage.setItem('cowengine_models', __COWENGINE_MODELS__); } catch(e) {}
        }
        function resizeCanvas(){
            var c=document.getElementById('canvas');if(!c)return;
            var r=window.devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;
            if(document.fullscreenElement===c){w=window.innerWidth;h=window.innerHeight;}
            c.width=Math.max(1,Math.floor(w*r));c.height=Math.max(1,Math.floor(h*r));
            if(typeof Module!=='undefined'&&Module)Module.canvas=c;
        }
        document.addEventListener('DOMContentLoaded',resizeCanvas);
        window.addEventListener('resize',resizeCanvas);
        document.addEventListener('fullscreenchange',resizeCanvas);
        // On-screen touch controls: left half is a virtual stick, right half
        // drags the camera. Both go through the engine's existing input paths
        // via the bridge in src/platform/Window.cpp — the stick presses the same
        // GLFW keys a keyboard would (so the movement script is untouched) and
        // the look pad reuses the pointer-lock mouse-delta route. Returns null
        // on non-touch devices, leaving desktop exactly as it was.
        function initTouchControls(){
            var coarse=false;
            try{coarse=window.matchMedia('(pointer: coarse)').matches;}catch(e){}
            if(!coarse||!(navigator.maxTouchPoints>0||'ontouchstart' in window))return null;
            // GLFW key codes (ASCII for printable keys; 340 = left shift).
            var K={W:87,A:65,S:83,D:68,SPACE:32,SHIFT:340,C:67,ESC:256};
            var RADIUS=56,DEAD=0.28,SPRINT=0.92;
            // The engine turns a delta into degrees as delta*5 (PlayerInputSystem)
            // *0.1 (Camera::sensitivity), so this is ~0.55 deg per CSS px dragged.
            // dpr is deliberately not applied here (unlike the mouse path):
            // finger travel is what matters, not pixel density.
            var LOOK=1.1;
            var layer=document.getElementById('touchControls');
            var stick=document.getElementById('stick'),knob=document.getElementById('stickKnob');
            var held={};
            function setKey(code,down){down=!!down;if(held[code]===down)return;held[code]=down;if(Module._cow_touch_key)Module._cow_touch_key(code,down?1:0);}
            var moveId=null,lookId=null,origin={x:0,y:0},last={x:0,y:0};
            function placeStick(x,y){stick.style.left=x+'px';stick.style.top=y+'px';}
            function releaseStick(){moveId=null;knob.style.transform='';stick.classList.remove('active');placeStick(100,window.innerHeight-116);setKey(K.W,0);setKey(K.A,0);setKey(K.S,0);setKey(K.D,0);setKey(K.SHIFT,0);}
            function applyStick(dx,dy){
                var len=Math.sqrt(dx*dx+dy*dy);
                if(len>RADIUS){dx=dx/len*RADIUS;dy=dy/len*RADIUS;len=RADIUS;}
                knob.style.transform='translate('+dx+'px,'+dy+'px)';
                var nx=dx/RADIUS,ny=dy/RADIUS;
                setKey(K.W,ny<-DEAD);setKey(K.S,ny>DEAD);setKey(K.A,nx<-DEAD);setKey(K.D,nx>DEAD);
                setKey(K.SHIFT,len/RADIUS>SPRINT);
            }
            function look(dx,dy){if(!Module._cow_touch_look)return;var s=(Module.mouseSensitivity||1)*LOOK;Module._cow_touch_look(dx*s,dy*s);}
            layer.addEventListener('touchstart',function(e){
                for(var i=0;i<e.changedTouches.length;i++){
                    var t=e.changedTouches[i];
                    if(t.clientX<window.innerWidth/2){
                        if(moveId!==null)continue;
                        moveId=t.identifier;origin.x=t.clientX;origin.y=t.clientY;
                        placeStick(t.clientX,t.clientY);stick.classList.add('active');knob.style.transform='';
                    }else{
                        if(lookId!==null)continue;
                        lookId=t.identifier;last.x=t.clientX;last.y=t.clientY;
                    }
                }
                e.preventDefault();
            },{passive:false});
            layer.addEventListener('touchmove',function(e){
                for(var i=0;i<e.changedTouches.length;i++){
                    var t=e.changedTouches[i];
                    if(t.identifier===moveId)applyStick(t.clientX-origin.x,t.clientY-origin.y);
                    else if(t.identifier===lookId){look(t.clientX-last.x,t.clientY-last.y);last.x=t.clientX;last.y=t.clientY;}
                }
                e.preventDefault();
            },{passive:false});
            function endTouch(e){
                for(var i=0;i<e.changedTouches.length;i++){
                    var t=e.changedTouches[i];
                    if(t.identifier===moveId)releaseStick();
                    else if(t.identifier===lookId)lookId=null;
                }
                e.preventDefault();
            }
            layer.addEventListener('touchend',endTouch,{passive:false});
            layer.addEventListener('touchcancel',endTouch,{passive:false});
            // Buttons stop propagation so a tap doesn't also grab the look finger.
            function bindButton(el,code){
                function down(e){e.preventDefault();e.stopPropagation();el.classList.add('held');setKey(code,1);}
                function up(e){e.preventDefault();e.stopPropagation();el.classList.remove('held');setKey(code,0);}
                el.addEventListener('touchstart',down,{passive:false});
                el.addEventListener('touchend',up,{passive:false});
                el.addEventListener('touchcancel',up,{passive:false});
            }
            bindButton(document.getElementById('jumpBtn'),K.SPACE);
            bindButton(document.getElementById('shootBtn'),K.C);
            // The gear presses Escape, which is what opens the engine's own
            // settings overlay. Once it is up, the stick moves the selection
            // (it presses W/S) and JUMP confirms (it presses Space) — so the
            // menu needs no touch controls of its own, and there is only one
            // menu implementation to maintain across desktop, web and phone.
            bindButton(document.getElementById('menuBtn'),K.ESC);
            releaseStick();
            window.addEventListener('resize',function(){if(moveId===null)releaseStick();});
            // No pointer lock exists on a phone, so open the gate mouse-look sits behind.
            if(Module._cow_touch_active)Module._cow_touch_active(1);
            return {show:function(){layer.classList.add('on');}};
        }
        var Module={
            noInitialRun:false,
            canvas:(function(){return document.getElementById('canvas');})(),
            print:function(){console.log.apply(console,arguments);},
            printErr:function(){console.error.apply(console,arguments);},
            onRuntimeInitialized:function(){
                Module.mouseSensitivity=1.0;
                document.getElementById('loadingOverlay').style.display='none';
                var s=document.getElementById('startOverlay');
                s.style.display='flex';
                var c=document.getElementById('canvas');
                c.addEventListener('contextmenu',function(e){e.preventDefault();});
                // Browsers reject a lock request made during the short cooldown
                // after a release, so swallow that promise rejection; the next
                // click succeeds.
                function lock(){if(!c.requestPointerLock)return;var p=c.requestPointerLock();if(p&&p.catch)p.catch(function(){});}
                // Non-null only on a touch device; desktop keeps the mouse path.
                var touch=initTouchControls();
                if(touch)s.querySelector('.hint').textContent='Left side to move, right side to look, buttons to jump and shoot';
                function go(){s.style.display='none';if(touch){touch.show();return;}c.focus();lock();}
                s.addEventListener('click',go);
                // Clicking the canvas while unlocked re-acquires pointer lock —
                // Tab/Escape release it, and the click is the gesture the
                // browser requires to grant it again.
                if(!touch)c.addEventListener('click',function(){if(document.pointerLockElement!==c)lock();});
                resizeCanvas();
            }
        };
    </script>
    <script async src="CowEngine.js"></script>
</body>
</html>)html";

namespace
{
    // Standard base64 encode — used to safely embed the scene JSON into HTML.
    std::string base64Encode(const std::string &input)
    {
        static const char table[] =
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
        std::string out;
        out.reserve(((input.size() + 2) / 3) * 4);
        for (std::size_t i = 0; i < input.size(); i += 3)
        {
            auto b0 = (unsigned char)input[i];
            auto b1 = i + 1 < input.size() ? (unsigned char)input[i + 1] : 0;
            auto b2 = i + 2 < input.size() ? (unsigned char)input[i + 2] : 0;
            out += table[b0 >> 2];
            out += table[((b0 & 3) << 4) | (b1 >> 4)];
            out += i + 1 < input.size() ? table[((b1 & 15) << 2) | (b2 >> 6)] : '=';
            out += i + 2 < input.size() ? table[b2 & 63] : '=';
        }
        return out;
    }

    // Replace a `var __COWENGINE_<NAME>__ = null;` sentinel with a base64-decoded
    // string literal so JS-side localStorage seeding picks it up.
    void patchHtmlSentinel(std::string &html, const std::string &varName, const std::string &payload)
    {
        if (payload.empty())
            return;
        std::string marker = "var " + varName + " = null;";
        auto pos = html.find(marker);
        if (pos == std::string::npos)
            return;
        std::string replacement = "var " + varName + " = atob('" + base64Encode(payload) + "');";
        html.replace(pos, marker.size(), replacement);
    }

    // Bake the multiplayer server config into the exported page by replacing the
    // `var __COWENGINE_SERVER__ = null;` sentinel with a JS object literal. Reads
    // COWENGINE_SERVER_WS / _WT / _CERTHASH from the environment at export time;
    // if none are set the page stays single-player (players can still opt in with
    // ?ws=/?wt= query params). Example:
    //   COWENGINE_SERVER_WS=wss://game.cowengine.com
    void patchServerConfig(std::string &html)
    {
        auto env = [](const char *k) -> std::string {
            const char *v = std::getenv(k);
            return v ? std::string(v) : std::string();
        };
        auto normalizeTransportUrl = [](std::string url) -> std::string {
            if (url.empty())
                return url;
            auto scheme_end = url.find("://");
            if (scheme_end == std::string::npos)
                return url;
            std::string scheme = url.substr(0, scheme_end);
            if (scheme != "ws" && scheme != "wss" && scheme != "http" && scheme != "https")
                return url;
            auto path_pos = url.find('/', scheme_end + 3);
            if (path_pos == std::string::npos)
            {
                if (scheme == "ws" || scheme == "wss")
                    url += "/net";
                return url;
            }
            if (path_pos == url.size() - 1 && (scheme == "ws" || scheme == "wss"))
                url += "net";
            return url;
        };
        std::string ws = env("COWENGINE_SERVER_WS");
        std::string wt = env("COWENGINE_SERVER_WT");
        std::string certHash = env("COWENGINE_SERVER_CERTHASH");
        if (ws.empty() && wt.empty())
            return;

        ws = normalizeTransportUrl(std::move(ws));
        wt = normalizeTransportUrl(std::move(wt));

        // These values are URLs / base64 hashes with no quotes or backslashes, so
        // a plain quoted literal is safe.
        std::string obj = "{";
        bool first = true;
        auto field = [&](const char *key, const std::string &val) {
            if (val.empty())
                return;
            if (!first)
                obj += ",";
            obj += key;
            obj += ":\"" + val + "\"";
            first = false;
        };
        field("ws", ws);
        field("wt", wt);
        field("certHash", certHash);
        obj += "}";

        const std::string marker = "var __COWENGINE_SERVER__ = null;";
        auto pos = html.find(marker);
        if (pos == std::string::npos)
            return;
        html.replace(pos, marker.size(), "var __COWENGINE_SERVER__ = " + obj + ";");
    }

    // Build a fresh game HTML blob from the embedded template, patched with the
    // exported scene plus snapshotted scripts and models.
    std::vector<unsigned char> makeGameHtml(const std::string &sceneJson,
                                            const std::string &scriptsJson,
                                            const std::string &modelsJson)
    {
        std::string html(kGameHtmlTemplate);
        patchHtmlSentinel(html, "__COWENGINE_SCENE__", sceneJson);
        patchHtmlSentinel(html, "__COWENGINE_SCRIPTS__", scriptsJson);
        patchHtmlSentinel(html, "__COWENGINE_MODELS__", modelsJson);
        patchServerConfig(html);
        return std::vector<unsigned char>(html.begin(), html.end());
    }

    // Pick which target maps to which slice of the embedded template archive.
    // In this build the editor only embeds the host-matching native template plus
    // the web template (the latter only when produced by the build).
    EmbeddedSlice sliceForTarget(GameBuilder::Target t)
    {
        switch (t)
        {
        case GameBuilder::Target::Linux:
            return EmbeddedSlice::NativeLinux;
        case GameBuilder::Target::Windows:
            return EmbeddedSlice::NativeWindows;
        case GameBuilder::Target::Web:
            return EmbeddedSlice::Web;
        }
        return EmbeddedSlice::NativeLinux;
    }

#if !defined(__EMSCRIPTEN__)
    // Cross-platform native folder picker. Returns empty string on cancel.
    std::string pickFolderNative()
    {
        auto fallbackPath = []() -> std::string
        {
#if defined(_WIN32)
            const char *home = std::getenv("USERPROFILE");
            if (!home || !*home)
                home = std::getenv("HOMEPATH");
#else
            const char *home = std::getenv("HOME");
#endif
            if (!home || !*home)
                return "";
            return std::string(home) + "/CowEngineBuilds";
        };
#if defined(_WIN32)
        BROWSEINFOA bi{};
        bi.lpszTitle = "Choose destination folder for game build";
        bi.ulFlags = BIF_USENEWUI | BIF_RETURNONLYFSDIRS;
        LPITEMIDLIST pidl = SHBrowseForFolderA(&bi);
        if (!pidl)
            return "";
        char path[MAX_PATH] = {};
        if (!SHGetPathFromIDListA(pidl, path))
            return "";
        CoTaskMemFree(pidl);
        return std::string(path);
#elif defined(__APPLE__)
        // osascript-based directory chooser
        FILE *p = popen("osascript -e 'POSIX path of (choose folder with prompt \"Choose destination folder for game build\")' 2>/dev/null", "r");
        if (!p)
            return "";
        char buf[4096] = {};
        std::string out;
        while (fgets(buf, sizeof(buf), p))
            out.append(buf);
        pclose(p);
        while (!out.empty() && (out.back() == '\n' || out.back() == '\r'))
            out.pop_back();
        return out;
#else
        // Linux: try zenity then kdialog
        auto try_cmd = [](const char *cmd) -> std::string
        {
            FILE *p = popen(cmd, "r");
            if (!p)
                return "";
            char buf[4096] = {};
            std::string out;
            while (fgets(buf, sizeof(buf), p))
                out.append(buf);
            int rc = pclose(p);
            if (rc != 0)
                return "";
            while (!out.empty() && (out.back() == '\n' || out.back() == '\r'))
                out.pop_back();
            return out;
        };
        std::string r = try_cmd("zenity --file-selection --directory --title='Choose destination folder for game build' 2>/dev/null");
        if (!r.empty())
            return r;
        r = try_cmd("kdialog --getexistingdirectory ~ --title 'Choose destination folder for game build' 2>/dev/null");
        if (!r.empty())
            return r;
        return fallbackPath();
#endif
    }
#endif

    // Write a file (creating parent dirs).
    bool writeBlob(const std::filesystem::path &outPath, const unsigned char *bytes, std::size_t size,
                   std::string &err)
    {
        namespace fs = std::filesystem;
        std::error_code ec;
        fs::create_directories(outPath.parent_path(), ec);
        std::ofstream f(outPath, std::ios::binary);
        if (!f)
        {
            err = "cannot open for write: " + outPath.string();
            return false;
        }
        f.write(reinterpret_cast<const char *>(bytes), static_cast<std::streamsize>(size));
        return static_cast<bool>(f);
    }

    // Serialize current scene + on-disk scripts/scene as a flat in-memory list of
    // {relativePath, bytes}. Used by the web zip path.
    void stageSceneSnapshot(Scene *scene, std::vector<StagedFile> &out)
    {
        if (!scene)
            return;
        // Save the live scene to a temp file we can read back as bytes.
        namespace fs = std::filesystem;
        std::error_code ec;
        fs::path tmpDir = fs::temp_directory_path(ec);
        if (ec || tmpDir.empty())
            tmpDir = ".";
        fs::path tmp = tmpDir / "cowengine_build_scene.json";
        fs::create_directories(tmp.parent_path(), ec);
        if (!scene->saveToJSON(tmp.string()))
            return;
        std::ifstream f(tmp, std::ios::binary);
        if (!f)
            return;
        std::ostringstream ss;
        ss << f.rdbuf();
        std::string s = ss.str();
        StagedFile sf;
        sf.path = "scenes/scene.json";
        sf.bytes.assign(s.begin(), s.end());
        out.push_back(std::move(sf));
    }

    // Walk `root` for files with `ext` and stage them at their relative paths.
    // Also accumulates them into a JSON object (path -> contents) suitable for
    // seeding into the game's localStorage via the HTML sentinel.
    void stageDirectoryAndJson(const std::string &root, const std::string &ext,
                               std::vector<StagedFile> &out, std::string &outJson)
    {
        namespace fs = std::filesystem;
        nlohmann::json j = nlohmann::json::object();
        std::error_code ec;
        fs::path rootPath(root);
        if (!fs::exists(rootPath, ec))
        {
            outJson.clear();
            return;
        }
        for (auto it = fs::recursive_directory_iterator(rootPath, ec);
             !ec && it != fs::recursive_directory_iterator(); it.increment(ec))
        {
            const fs::directory_entry &entry = *it;
            if (!entry.is_regular_file(ec))
                continue;
            if (entry.path().extension() != ext)
                continue;
            std::ifstream f(entry.path(), std::ios::binary);
            if (!f)
                continue;
            std::ostringstream ss;
            ss << f.rdbuf();
            std::string content = ss.str();
            fs::path rel = fs::relative(entry.path(), rootPath, ec);
            if (ec)
                continue;
            std::string relStr = root + "/" + rel.generic_string();
            StagedFile sf;
            sf.path = relStr;
            sf.bytes.assign(content.begin(), content.end());
            out.push_back(std::move(sf));
            j[relStr] = content;
        }
        outJson = j.empty() ? std::string() : j.dump();
    }
} // namespace

bool GameBuilder::isTargetAvailable(Target t)
{
#if defined(__EMSCRIPTEN__)
    // Web editor can only export web builds.
    return t == Target::Web;
#else
    // A target is available if an embedded slice for it exists.
    return EmbeddedTemplate_hasSlice(sliceForTarget(t));
#endif
}

const char *GameBuilder::targetLabel(Target t)
{
    switch (t)
    {
    case Target::Linux:
        return "Linux Game...";
    case Target::Windows:
        return "Windows Game...";
    case Target::Web:
        return "Web Game (.zip)...";
    }
    return "?";
}

GameBuilder::Result GameBuilder::build(Target t, Scene *scene,
                                       const std::function<void(const std::string &)> &log)
{
    Result r;
    auto say = [&](const std::string &m)
    { if (log) log(m); };

    if (!isTargetAvailable(t))
    {
        r.message = "Target not available on this platform.";
        return r;
    }

    EmbeddedSlice slice = sliceForTarget(t);
    std::size_t count = EmbeddedTemplate_fileCount(slice);

#if defined(__EMSCRIPTEN__)
    // Web: build a flat list of {path, bytes} and hand it to JS for zipping + download.
    // The JS side is provided by EmbeddedTemplate_jsDownloadZip (declared in
    // EmbeddedTemplate.hpp).
    if (count == 0)
    {
        r.message = "Web template missing. Build game-web and rebuild the editor.";
        return r;
    }
    say("Packaging web build...");
    std::vector<StagedFile> staged;
    for (std::size_t i = 0; i < count; ++i)
    {
        EmbeddedFile ef = EmbeddedTemplate_fileAt(slice, i);
        // Drop CowEngine.html from the template — we emit a fresh index.html
        // below, and the running game never reads CowEngine.html anyway.
        if (std::string(ef.relativePath) == "CowEngine.html")
            continue;
        StagedFile sf;
        sf.path = ef.relativePath;
        sf.bytes.assign(ef.data, ef.data + ef.size);
        staged.push_back(std::move(sf));
    }
    // Snapshot the live scene + scripts + models for the HTML localStorage seed.
    // The running web game reads these from localStorage (see Application::init),
    // not from on-disk files inside the unzipped folder, so we do NOT add the
    // raw scene/script/model files to the zip — they would just be a copy of
    // what's already in CowEngine.data plus a third copy in HTML base64.
    std::string sceneJson;
    {
        std::vector<StagedFile> sceneOnly;
        stageSceneSnapshot(scene, sceneOnly);
        if (!sceneOnly.empty())
            sceneJson.assign(sceneOnly[0].bytes.begin(), sceneOnly[0].bytes.end());
    }
    std::string scriptsJson, modelsJson;
    {
        std::vector<StagedFile> discarded;
        stageDirectoryAndJson("scripts", ".cow", discarded, scriptsJson);
        stageDirectoryAndJson("models", ".obj", discarded, modelsJson);
    }
    {
        auto freshHtml = makeGameHtml(sceneJson, scriptsJson, modelsJson);
        StagedFile si;
        si.path = "index.html"; si.bytes = freshHtml;
        staged.push_back(std::move(si));
    }
    EmbeddedTemplate_jsDownloadZip(staged, "CowEngineGame.zip");
    r.ok = true;
    r.message = "Download started (CowEngineGame.zip)";
    return r;
#else
    std::string dir = pickFolderNative();
    if (dir.empty())
    {
        r.message = "Cancelled.";
        return r;
    }
    namespace fs = std::filesystem;
    fs::path root(dir);
    // Drop our payload into a clearly-named subfolder so we never blow away
    // unrelated files in the user's chosen directory.
    fs::path target = root / "CowEngineGame";
    std::error_code ec;
    fs::create_directories(target, ec);
    say("Writing build to " + target.string());

    std::string err;
    for (std::size_t i = 0; i < count; ++i)
    {
        EmbeddedFile ef = EmbeddedTemplate_fileAt(slice, i);
        // Skip CowEngine.html from the template — we write a fresh index.html
        // below (the web target) and native targets don't use HTML at all.
        if (std::string(ef.relativePath) == "CowEngine.html")
            continue;
        if (!writeBlob(target / ef.relativePath, ef.data, ef.size, err))
        {
            r.message = err;
            return r;
        }
    }

    // Overlay the user's current in-memory scene last so it wins over any
    // scene baked into the template.
    std::string sceneJson;
    if (scene)
    {
        fs::path sceneDest = target / "scenes" / "scene.json";
        if (scene->saveToJSON(sceneDest.string()))
        {
            say("Wrote live scene.json");
            std::ifstream sf(sceneDest, std::ios::binary);
            if (sf)
            {
                std::ostringstream ss;
                ss << sf.rdbuf();
                sceneJson = ss.str();
            }
        }
    }
    // Snapshot scripts/models alongside the scene so a native export of a web
    // game still carries the user's latest edits via the HTML localStorage seed.
    // (For Linux/Windows native targets the HTML is irrelevant; the helper just
    // returns empty json when the directories are absent.)
    std::string scriptsJson, modelsJson;
    {
        std::vector<StagedFile> ignored;
        stageDirectoryAndJson("scripts", ".cow", ignored, scriptsJson);
        stageDirectoryAndJson("models", ".obj", ignored, modelsJson);
    }
    // Generate a fresh index.html from the embedded template with the current
    // scene baked in. Native targets (Linux/Windows) ignore the HTML entirely,
    // but it costs nothing to write and keeps the web target consistent.
    {
        auto freshHtml = makeGameHtml(sceneJson, scriptsJson, modelsJson);
        std::ofstream f(target / "index.html", std::ios::binary);
        f.write(reinterpret_cast<const char *>(freshHtml.data()), freshHtml.size());
        if (!sceneJson.empty())
            say("Injected scene into index.html");
    }

    r.ok = true;
    r.message = target.string();
    return r;
#endif
}

// ============================================================================
// Publishing
// ============================================================================
//
// The upload is the same {path: contents} map the exporter already stages, so
// nothing new has to be produced on this side:
//
//   { "title": ..., "description": ..., "files": { "scenes/scene.json": "...",
//     "scripts/x.cow": "...", "models/y.obj": "..." } }
//
// Edit keys are the only way to update a published game (publishing is
// anonymous), so they are persisted next to the project — localStorage on the
// web, a file in the working directory natively. Losing one means the game can
// never be updated again, which is why the UI shows it prominently on success.

namespace
{
    const char *kPublishKeysStore = "cowengine_publish_keys";

    GameBuilder::PublishStatus g_publish;

#if defined(__EMSCRIPTEN__)
    EM_JS(char *, em_api_base, (), {
        // Baked into the editor shell at deploy time; ?api= overrides it so a
        // local control plane can be driven from the hosted editor.
        var base = '';
        try {
            var q = new URLSearchParams(location.search);
            base = q.get('api') || (typeof __COWENGINE_API__ === 'string' ? __COWENGINE_API__ : '');
        } catch (e) { }
        return stringToNewUTF8(base || '');
    });

    EM_JS(char *, em_kv_get, (const char *key), {
        var v = '';
        try { v = localStorage.getItem(UTF8ToString(key)) || ''; } catch (e) { }
        return stringToNewUTF8(v);
    });

    EM_JS(void, em_kv_set, (const char *key, const char *value), {
        try { localStorage.setItem(UTF8ToString(key), UTF8ToString(value)); } catch (e) { }
    });

    // state: 0 idle, 1 pending, 2 complete (check status), 3 transport failure
    EM_JS(void, em_publish_start, (const char *url, const char *method,
                                   const char *editKey, const char *body), {
        window.__cowPublish = { state: 1, status: 0, text: '' };
        var headers = { 'Content-Type': 'application/json' };
        var key = UTF8ToString(editKey);
        if (key) headers['X-Cow-Edit-Key'] = key;
        fetch(UTF8ToString(url), {
            method: UTF8ToString(method),
            headers: headers,
            body: UTF8ToString(body),
        }).then(function (r) {
            window.__cowPublish.status = r.status;
            return r.text();
        }).then(function (t) {
            window.__cowPublish.text = t;
            window.__cowPublish.state = 2;
        }).catch(function (e) {
            window.__cowPublish.text = String(e);
            window.__cowPublish.state = 3;
        });
    });

    EM_JS(int, em_publish_state, (), {
        return window.__cowPublish ? window.__cowPublish.state : 0;
    });
    EM_JS(int, em_publish_status, (), {
        return window.__cowPublish ? window.__cowPublish.status : 0;
    });
    EM_JS(char *, em_publish_text, (), {
        return stringToNewUTF8(window.__cowPublish ? (window.__cowPublish.text || '') : '');
    });

    std::string takeJsString(char *p)
    {
        if (!p)
            return {};
        std::string s(p);
        free(p);
        return s;
    }
#endif

    // Persisted publish state: { "last": "<gameId>", "keys": { "<gameId>": "<key>" } }
    nlohmann::json loadPublishStore()
    {
        std::string raw;
#if defined(__EMSCRIPTEN__)
        raw = takeJsString(em_kv_get(kPublishKeysStore));
#else
        std::ifstream f(std::string(kPublishKeysStore) + ".json");
        if (f)
        {
            std::ostringstream ss;
            ss << f.rdbuf();
            raw = ss.str();
        }
#endif
        if (raw.empty())
            return nlohmann::json::object();
        nlohmann::json j = nlohmann::json::parse(raw, nullptr, false);
        return j.is_object() ? j : nlohmann::json::object();
    }

    void savePublishStore(const nlohmann::json &j)
    {
        const std::string raw = j.dump();
#if defined(__EMSCRIPTEN__)
        em_kv_set(kPublishKeysStore, raw.c_str());
#else
        std::ofstream f(std::string(kPublishKeysStore) + ".json", std::ios::trunc);
        if (f)
            f << raw;
#endif
    }

    std::string editKeyFor(const std::string &gameId)
    {
        if (gameId.empty())
            return {};
        nlohmann::json store = loadPublishStore();
        if (!store.contains("keys") || !store["keys"].is_object())
            return {};
        auto it = store["keys"].find(gameId);
        return (it != store["keys"].end() && it->is_string()) ? it->get<std::string>()
                                                              : std::string();
    }

    void rememberPublish(const std::string &gameId, const std::string &editKey)
    {
        nlohmann::json store = loadPublishStore();
        if (!store.contains("keys") || !store["keys"].is_object())
            store["keys"] = nlohmann::json::object();
        if (!editKey.empty())
            store["keys"][gameId] = editKey;
        store["last"] = gameId;
        savePublishStore(store);
    }

    // Interpret a completed HTTP exchange. Shared by the web and native paths so
    // the success and failure wording cannot drift between them.
    void applyPublishResult(long status, const std::string &payload)
    {
        nlohmann::json j = nlohmann::json::parse(payload, nullptr, false);

        if (status < 200 || status >= 300)
        {
            std::string msg = "Publish failed (HTTP " + std::to_string(status) + ")";
            if (j.is_object() && j.contains("error") && j["error"].is_string())
                msg += ": " + j["error"].get<std::string>();
            else if (!payload.empty())
                msg += ": " + payload.substr(0, 200);
            g_publish.state = GameBuilder::PublishState::Failed;
            g_publish.message = msg;
            return;
        }
        if (!j.is_object() || !j.contains("id"))
        {
            g_publish.state = GameBuilder::PublishState::Failed;
            g_publish.message = "Publish succeeded but the reply was not understood: " +
                                payload.substr(0, 200);
            return;
        }

        g_publish.state = GameBuilder::PublishState::Success;
        g_publish.gameId = j["id"].get<std::string>();
        g_publish.version = j.value("version", 0);
        g_publish.editKey = j.value("edit_key", std::string());
        rememberPublish(g_publish.gameId, g_publish.editKey);
        g_publish.message = "Published " + g_publish.gameId + " (version " +
                            std::to_string(g_publish.version) + ")";
    }
} // namespace

std::string GameBuilder::apiBase()
{
#if defined(__EMSCRIPTEN__)
    std::string base = takeJsString(em_api_base());
#else
    const char *env = std::getenv("COWENGINE_API");
    std::string base = env ? env : "";
#endif
    while (!base.empty() && base.back() == '/')
        base.pop_back();
    return base;
}

bool GameBuilder::publishAvailable()
{
    return !apiBase().empty();
}

std::string GameBuilder::lastPublishedId()
{
    nlohmann::json store = loadPublishStore();
    auto it = store.find("last");
    return (it != store.end() && it->is_string()) ? it->get<std::string>() : std::string();
}

std::string GameBuilder::buildBundleJson(Scene *scene, const std::string &title,
                                         const std::string &description)
{
    nlohmann::json files = nlohmann::json::object();

    // The live scene, via the same save path the exporter uses, so what gets
    // published is byte-identical to what a local export would contain. That
    // matters beyond tidiness: the client seeds its world from this same bundle,
    // and NetIds are derived from scene load order, so any divergence between
    // what the server loads and what the client loads breaks collision.
    std::vector<StagedFile> staged;
    stageSceneSnapshot(scene, staged);
    for (const StagedFile &sf : staged)
        files[sf.path] = std::string(sf.bytes.begin(), sf.bytes.end());

    for (const auto &dir : {std::pair<const char *, const char *>{"scripts", ".cow"},
                            std::pair<const char *, const char *>{"models", ".obj"}})
    {
        std::vector<StagedFile> more;
        std::string json;
        stageDirectoryAndJson(dir.first, dir.second, more, json);
        for (const StagedFile &sf : more)
            files[sf.path] = std::string(sf.bytes.begin(), sf.bytes.end());
    }

    nlohmann::json envelope;
    envelope["title"] = title;
    envelope["description"] = description;
    envelope["files"] = std::move(files);
    return envelope.dump();
}

bool GameBuilder::publishStart(Scene *scene, const std::string &title,
                               const std::string &description,
                               const std::function<void(const std::string &)> &log)
{
    auto note = [&](const std::string &s) { if (log) log(s); };

    if (g_publish.state == PublishState::Pending)
    {
        note("A publish is already in progress.");
        return false;
    }
    const std::string base = apiBase();
    if (base.empty())
    {
        g_publish = PublishStatus{PublishState::Failed,
                                  "Publishing is not configured (no server URL).", {}, {}, 0};
        return false;
    }
    if (!scene)
    {
        g_publish = PublishStatus{PublishState::Failed, "No active scene to publish.", {}, {}, 0};
        return false;
    }

    // Update the existing game when we still hold its key; otherwise create one.
    const std::string previous = lastPublishedId();
    const std::string key = editKeyFor(previous);
    const bool update = !previous.empty() && !key.empty();
    const std::string url = update ? base + "/api/games/" + previous : base + "/api/games";
    const char *method = update ? "PUT" : "POST";

    note(update ? "Updating " + previous + "..." : "Publishing a new game...");
    const std::string body = buildBundleJson(scene, title, description);
    note("Bundle is " + std::to_string(body.size() / 1024) + " KiB.");

    g_publish = PublishStatus{PublishState::Pending, "Uploading...", update ? previous : "", {}, 0};

#if defined(__EMSCRIPTEN__)
    em_publish_start(url.c_str(), method, key.c_str(), body.c_str());
    return true;
#else
    // Native path shells out to curl. The editor is a developer tool here and a
    // publish is a deliberate, occasional action, so one stalled frame is a fair
    // price for not linking an HTTP client into every editor build.
    namespace fs = std::filesystem;
    std::error_code ec;
    fs::path tmp = fs::temp_directory_path(ec);
    if (ec || tmp.empty())
        tmp = ".";
    fs::path bodyPath = tmp / "cowengine_publish_body.json";
    {
        std::ofstream f(bodyPath, std::ios::binary | std::ios::trunc);
        if (!f)
        {
            g_publish = PublishStatus{PublishState::Failed,
                                      "Could not stage the upload: " + bodyPath.string(), {}, {}, 0};
            return false;
        }
        f << body;
    }

    std::string cmd = "curl -sS -X " + std::string(method) +
                      " -H 'Content-Type: application/json'";
    if (!key.empty())
        cmd += " -H 'X-Cow-Edit-Key: " + key + "'";
    cmd += " -w '\\n%{http_code}' --data-binary @" + bodyPath.string() + " '" + url + "' 2>&1";

    std::string out;
    if (FILE *pipe = popen(cmd.c_str(), "r"))
    {
        char buf[4096];
        while (fgets(buf, sizeof(buf), pipe))
            out += buf;
        pclose(pipe);
    }
    fs::remove(bodyPath, ec);

    // The body and the trailing status code are separated by the last newline.
    long status = 0;
    std::string payload = out;
    if (auto nl = out.find_last_of('\n'); nl != std::string::npos)
    {
        status = std::strtol(out.c_str() + nl + 1, nullptr, 10);
        payload = out.substr(0, nl);
    }
    applyPublishResult(status, payload);
    return true;
#endif
}

GameBuilder::PublishStatus GameBuilder::publishPoll()
{
#if defined(__EMSCRIPTEN__)
    if (g_publish.state == PublishState::Pending)
    {
        const int js = em_publish_state();
        if (js == 2)
            applyPublishResult(em_publish_status(), takeJsString(em_publish_text()));
        else if (js == 3)
        {
            g_publish.state = PublishState::Failed;
            g_publish.message = "Could not reach the server: " + takeJsString(em_publish_text());
        }
    }
#endif
    return g_publish;
}
